# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
pod 'Firebase'
pod 'FirebaseMessaging'
pod 'GoogleToolboxForMac'
pod 'Protobuf'

target 'PerSoNClinic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Quit4Good

end

target 'PerSoNClinic_Production' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Quit4Good_Production

end
